# Generated by Django 3.2.4 on 2021-08-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_cliente_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='rut',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
